#!/bin/sh
### BEGIN INIT INFO
# Provides:          NovgorodWeatherBot
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       start NovgorodWeatherBot bot
### END INIT INFO

SCRIPT=/home/fut33v/NovgorodWeatherBot/start.sh
WORKINGDIR=/home/fut33v/NovgorodWeatherBot/
RUNAS=fut33v
PIDFILE=/home/fut33v/NovgorodWeatherBot/NovgorodWeatherBot.pid

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  su -c "start-stop-daemon --start --quiet --background --make-pidfile --no-close --chuid $RUNAS --pidfile $PIDFILE --chdir $WORKINGDIR --exec $SCRIPT"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
